# ===================================================================== #
#  An R package by Certe:                                               #
#  https://github.com/certe-medical-epidemiology                        #
#                                                                       #
#  Licensed as GPL-v2.0.                                                #
#                                                                       #
#  Developed at non-profit organisation Certe Medical Diagnostics &     #
#  Advice, department of Medical Epidemiology.                          #
#                                                                       #
#  This R package is free software; you can freely use and distribute   #
#  it for both personal and commercial purposes under the terms of the  #
#  GNU General Public License version 2.0 (GNU GPL-2), as published by  #
#  the Free Software Foundation.                                        #
#                                                                       #
#  We created this package for both routine data analysis and academic  #
#  research and it was publicly released in the hope that it will be    #
#  useful, but it comes WITHOUT ANY WARRANTY OR LIABILITY.              #
# ===================================================================== #

#' List of DI Columns
#'
#' @keywords internal
#' @export
di <- list(AanmaakDatum = "AanmaakDatum",
           AanmaakTijd = "AanmaakTijd",
           AanmaakTimestamp = "AanmaakTimestamp",
           AantalUitgevoerd = "AantalUitgevoerd",
           AanvragerAdres = "AanvragerAdres",
           AanvragerAGB = "AanvragerAGB",
           AanvragerCode = "AanvragerCode",
           AanvragerLand = "AanvragerLand",
           AanvragerNaam = "AanvragerNaam",
           AanvragerPlaats = "AanvragerPlaats",
           AanvragerPostcode = "AanvragerPostcode",
           AanvragerProvincie = "AanvragerProvincie",
           AanvragerSoort = "AanvragerSoort",
           AanvragerSpecialisme = "AanvragerSpecialisme",
           AfnameDag = "AfnameDag",
           AfnameDatum = "AfnameDatum",
           AfnameJaar = "AfnameJaar",
           AfnameJaarMaand = "AfnameJaarMaand",
           AfnameKwartaal = "AfnameKwartaal",
           AfnameMaand = "AfnameMaand",
           AfnameMaandNaam = "AfnameMaandNaam",
           AfnameTijd = "AfnameTijd",
           AfnameTijdvak = "AfnameTijdvak",
           AfnameWeek = "AfnameWeek",
           AfnameWeekdag = "AfnameWeekdag",
           AfnameWeekdagNummer = "AfnameWeekdagNummer",
           Apparaat = "Apparaat",
           AutorisatieDatum = "AutorisatieDatum",
           AutorisatieTijd = "AutorisatieTijd",
           AutorisatieTijdvak = "AutorisatieTijdvak",
           AutorisatieTimestamp = "AutorisatieTimestamp",
           BepalingCode = "BepalingCode",
           BepalingInteresseCategorie = "BepalingInteresseCategorie",
           BepalingInteresseSubcategorie = "BepalingInteresseSubcategorie",
           BepalingNaam = "BepalingNaam",
           Bronlocatie = "Bronlocatie",
           Bronsysteem = "Bronsysteem",
           BuitenNorm = "BuitenNorm",
           Commentaar = "Commentaar",
           CommentaarInternIsolaat = "CommentaarInternIsolaat",
           CommentaarIsolaat = "CommentaarIsolaat",
           `Confirmatie-Autorisatie` = "Confirmatie-Autorisatie",
           ConfirmatieDatum = "ConfirmatieDatum",
           ConfirmatieTijd = "ConfirmatieTijd",
           ConfirmatieTijdvak = "ConfirmatieTijdvak",
           ConfirmatieTimestamp = "ConfirmatieTimestamp",
           `Ct-waarde` = "Ct-waarde",
           DigitaalAangevraagdSoort = "DigitaalAangevraagdSoort",
           EersteUitslagInResultaat = "EersteUitslagInResultaat",
           ExternLabNaam = "ExternLabNaam",
           IsAeroob = "IsAeroob",
           IsARE = "IsARE",
           IsAsielzoeker = "IsAsielzoeker",
           IsBactKweek = "IsBactKweek",
           IsBactKweekBoolean = "IsBactKweekBoolean",
           IsBRMO = "IsBRMO",
           IsBuitenNorm = "IsBuitenNorm",
           IsCPE = "IsCPE",
           IsDigitaalAangevraagd = "IsDigitaalAangevraagd",
           IsESBL = "IsESBL",
           IsGecontamineerdeBloedkweek = "IsGecontamineerdeBloedkweek",
           IsHeeftAntibiogram = "IsHeeftAntibiogram",
           IsIC = "IsIC",
           IsIsolaatPositief = "IsIsolaatPositief",
           IsKlinisch = "IsKlinisch",
           IsMRGNS = "IsMRGNS",
           IsMRSA = "IsMRSA",
           IsolaatAanmaakTimestamp = "IsolaatAanmaakTimestamp",
           IsolaatBeoordeling = "IsolaatBeoordeling",
           IsolaatBeoordelingCode = "IsolaatBeoordelingCode",
           IsolaatBeschikbaarTimestamp = "IsolaatBeschikbaarTimestamp",
           IsolaatVolgnr = "IsolaatVolgnr",
           IsPatient = "IsPatient",
           IsTechnischGevalideerd = "IsTechnischGevalideerd",
           KlinischeGegevens = "KlinischeGegevens",
           Kostenplaats = "Kostenplaats",
           KostenplaatsCode = "KostenplaatsCode",
           MateriaalCode = "MateriaalCode",
           MateriaalGroep = "MateriaalGroep",
           MateriaalHerkomstnaam = "MateriaalHerkomstnaam",
           MateriaalKorteNaam = "MateriaalKorteNaam",
           MateriaalNaam = "MateriaalNaam",
           `Micro-organisme` = "Micro-organisme",
           `Micro-organismeCode` = "Micro-organismeCode",
           `Micro-organismeCodeRuw` = "Micro-organismeCodeRuw",
           `Micro-organismeFamilie` = "Micro-organismeFamilie",
           `Micro-organismeGenus` = "Micro-organismeGenus",
           `Micro-organismeNaam` = "Micro-organismeNaam",
           `Micro-organismeSpecies` = "Micro-organismeSpecies",
           Monsternummer = "Monsternummer",
           NegeerBijDoorlooptijden = "NegeerBijDoorlooptijden",
           NormDoorlooptijd = "NormDoorlooptijd",
           `Ontvangst-Autorisatie` = "Ontvangst-Autorisatie",
           `Ontvangst-Resultaatinvoer` = "Ontvangst-Resultaatinvoer",
           OntvangstDag = "OntvangstDag",
           OntvangstDatum = "OntvangstDatum",
           OntvangstJaar = "OntvangstJaar",
           OntvangstJaarMaand = "OntvangstJaarMaand",
           OntvangstKwartaal = "OntvangstKwartaal",
           OntvangstLocatieCode = "OntvangstLocatieCode",
           OntvangstLocatieNaam = "OntvangstLocatieNaam",
           OntvangstMaand = "OntvangstMaand",
           OntvangstMaandNaam = "OntvangstMaandNaam",
           OntvangstTijd = "OntvangstTijd",
           OntvangstTimestamp = "OntvangstTimestamp",
           OntvangstWeek = "OntvangstWeek",
           OntvangstWeekdag = "OntvangstWeekdag",
           OntvangstWeekdagNummer = "OntvangstWeekdagNummer",
           Ontvangstwijze = "Ontvangstwijze",
           Opname = "Opname",
           OpnameType = "OpnameType",
           OrderCompleetDatum = "OrderCompleetDatum",
           OrderCompleetTijd = "OrderCompleetTijd",
           Ordernummer = "Ordernummer",
           OrderStatus = "OrderStatus",
           PatientBSN = "PatientBSN",
           PatientGeboorteDatum = "PatientGeboorteDatum",
           PatientGeboortedatum = "PatientGeboortedatum",
           PatientGeslacht = "PatientGeslacht",
           PatientID = "PatientID",
           PatientInstellingcode = "PatientInstellingcode",
           PatientLand = "PatientLand",
           PatientLeeftijd = "PatientLeeftijd",
           PatientLeeftijdCategorie = "PatientLeeftijdCategorie",
           PatientPlaats = "PatientPlaats",
           PatientPostcode = "PatientPostcode",
           PatientProvincie = "PatientProvincie",
           PatientType = "PatientType",
           Personeel = "Personeel",
           PositiefOfNegatief = "PositiefOfNegatief",
           Resultaat = "Resultaat",
           ResultaatDatum = "ResultaatDatum",
           ResultaatEenheid = "ResultaatEenheid",
           `Resultaatinvoer-Confirmatie` = "Resultaatinvoer-Confirmatie",
           ResultaatStatus = "ResultaatStatus",
           ResultaatTbvLijnmanagement = "ResultaatTbvLijnmanagement",
           ResultaatTijd = "ResultaatTijd",
           ResultaatTijdvak = "ResultaatTijdvak",
           ResultaatTimestamp = "ResultaatTimestamp",
           ResultaatUrgentie = "ResultaatUrgentie",
           Ringonderzoek = "Ringonderzoek",
           SoortKweek = "SoortKweek",
           UitvoerendeLocatieNaam = "UitvoerendeLocatieNaam",
           Urgentie = "Urgentie",
           Vakgebied = "Vakgebied",
           WerkplekNaam = "WerkplekNaam",
           Ziekenhuis = "Ziekenhuis",
           ZiekenhuisAfdeling = "ZiekenhuisAfdeling",
           ZiekenhuisAfdelingCode = "ZiekenhuisAfdelingCode",
           ZiekenhuisGroep = "ZiekenhuisGroep",
           Zorglijn = "Zorglijn")
