# ===================================================================== #
#  An R package by Certe:                                               #
#  https://github.com/certe-medical-epidemiology                        #
#                                                                       #
#  Licensed as GPL-v2.0.                                                #
#                                                                       #
#  Developed at non-profit organisation Certe Medical Diagnostics &     #
#  Advice, department of Medical Epidemiology.                          #
#                                                                       #
#  This R package is free software; you can freely use and distribute   #
#  it for both personal and commercial purposes under the terms of the  #
#  GNU General Public License version 2.0 (GNU GPL-2), as published by  #
#  the Free Software Foundation.                                        #
#                                                                       #
#  We created this package for both routine data analysis and academic  #
#  research and it was publicly released in the hope that it will be    #
#  useful, but it comes WITHOUT ANY WARRANTY OR LIABILITY.              #
# ===================================================================== #

#' List of GLIMS Columns
#'
#' @keywords internal
#' @export
gl <- list(Aantal = "Aantal",
           AanvragerAGB = "AanvragerAGB",
           AanvragerCode = "AanvragerCode",
           AanvragerNaam = "AanvragerNaam",
           AanvragerSoort = "AanvragerSoort",
           AanvragerSpecialisme = "AanvragerSpecialisme",
           AfdelingAfnametype = "AfdelingAfnametype",
           AfdelingCode = "AfdelingCode",
           AfdelingNaam = "AfdelingNaam",
           AfnameJaar = "AfnameJaar",
           BepalingCode = "BepalingCode",
           BepalingNaamKort = "BepalingNaamKort",
           BepalingOmschrijving = "BepalingOmschrijving",
           BepalingUrgentie = "BepalingUrgentie",
           CommentaarExtern = "CommentaarExtern",
           CommentaarExternTekst = "CommentaarExternTekst",
           CommentaarIntern = "CommentaarIntern",
           CommentaarInternTekst = "CommentaarInternTekst",
           `CT-waarde` = "CT-waarde",
           DatumOrderOntvangst = "DatumOrderOntvangst",
           DatumOrderOntvangst2 = "DatumOrderOntvangst2",
           DatumTijdIsolaatAanmaak = "DatumTijdIsolaatAanmaak",
           DatumTijdIsolaatBeschikbaar = "DatumTijdIsolaatBeschikbaar",
           DatumTijdIsolaatConfirmatie = "DatumTijdIsolaatConfirmatie",
           DatumTijdIsolaatTestBeschikbaar = "DatumTijdIsolaatTestBeschikbaar",
           DatumTijdIsolaatTestConfirmatie = "DatumTijdIsolaatTestConfirmatie",
           DatumTijdIsolaatTestValidatie = "DatumTijdIsolaatTestValidatie",
           DatumTijdIsolaatValidatie = "DatumTijdIsolaatValidatie",
           DatumTijdMcraConfirmatie = "DatumTijdMcraConfirmatie",
           DatumTijdMcraValidatie = "DatumTijdMcraValidatie",
           DatumTijdOrderAfname = "DatumTijdOrderAfname",
           DatumTijdOrderCompleet = "DatumTijdOrderCompleet",
           DatumTijdOrderOntvangst = "DatumTijdOrderOntvangst",
           DatumTijdResultaatAutorisatie = "DatumTijdResultaatAutorisatie",
           DatumTijdResultaatBeschikbaar = "DatumTijdResultaatBeschikbaar",
           DatumTijdResultaatConfirmatie = "DatumTijdResultaatConfirmatie",
           InstellingCode = "InstellingCode",
           InstellingNaam = "InstellingNaam",
           IsAangevraagd = "IsAangevraagd",
           IsAntibiogramAanwezig = "IsAntibiogramAanwezig",
           IsBactkweek = "IsBactkweek",
           IsKweekPositief = "IsKweekPositief",
           IsolaatCommentaarExtern = "IsolaatCommentaarExtern",
           IsolaatCommentaarExternTekst = "IsolaatCommentaarExternTekst",
           IsolaatCommentaarIntern = "IsolaatCommentaarIntern",
           IsolaatCommentaarInternTekst = "IsolaatCommentaarInternTekst",
           IsolaatPositiefOfNegatief = "IsolaatPositiefOfNegatief",
           IsolaatReportable = "IsolaatReportable",
           IsolaatStatus = "IsolaatStatus",
           IsolaatTestCode = "IsolaatTestCode",
           IsolaatTestNaam = "IsolaatTestNaam",
           IsolaatTestResultaat = "IsolaatTestResultaat",
           IsolaatTestResultaatTekst = "IsolaatTestResultaatTekst",
           IsolaatTestStatus = "IsolaatTestStatus",
           IsolaatVolgnummer = "IsolaatVolgnummer",
           IsolaatWaarderingCode = "IsolaatWaarderingCode",
           IsolaatWaarderingNaam = "IsolaatWaarderingNaam",
           IsolaatWaarderingPositief = "IsolaatWaarderingPositief",
           IsPositief = "IsPositief",
           Kiemgetal = "Kiemgetal",
           KlinischeGegevens = "KlinischeGegevens",
           KopierapportOntvangerCode = "KopierapportOntvangerCode",
           KopierapportOntvangerNaam = "KopierapportOntvangerNaam",
           MateriaalCode = "MateriaalCode",
           MateriaalCode2 = "MateriaalCode2",
           MateriaalExtraInfo = "MateriaalExtraInfo",
           MateriaalKorteNaam = "MateriaalKorteNaam",
           MateriaalOmschrijving = "MateriaalOmschrijving",
           MateriaalVariabeleCode = "MateriaalVariabeleCode",
           MateriaalVariabeleNaam = "MateriaalVariabeleNaam",
           McraStatus = "McraStatus",
           MeetEenheid = "MeetEenheid",
           MicroOrganisme = "MicroOrganisme",
           MicroOrganismeCode = "MicroOrganismeCode",
           MicroOrganismeNaam = "MicroOrganismeNaam",
           MicrobiolStationNaam = "MicrobiolStationNaam",
           MicrobiolWorkplaceNaam = "MicrobiolWorkplaceNaam",
           Monsternummer = "Monsternummer",
           Monsternummer2 = "Monsternummer2",
           Ontvangstwijze = "Ontvangstwijze",
           Ordernummer = "Ordernummer",
           OrderStatus = "OrderStatus",
           OrganisatieCode = "OrganisatieCode",
           OrganisatieNaam = "OrganisatieNaam",
           PatientBSN = "PatientBSN",
           PatientExternalId = "PatientExternalId",
           PatientGeboortedatum = "PatientGeboortedatum",
           PatientGeslacht = "PatientGeslacht",
           PatientID = "PatientID",
           PatientInstellingCode = "PatientInstellingCode",
           PatientLeeftijd = "PatientLeeftijd",
           PatientLeeftijdRange = "PatientLeeftijdRange",
           PatientNaam = "PatientNaam",
           PatientPlaats = "PatientPlaats",
           PatientPostcode4 = "PatientPostcode4",
           Regiegroep = "Regiegroep",
           Resultaat = "Resultaat",
           ResultaatStatus = "ResultaatStatus",
           ResultaatTekst = "ResultaatTekst",
           StationNaam = "StationNaam",
           UitvoerLocatieNaam = "UitvoerLocatieNaam",
           VerzendLocatieNaam = "VerzendLocatieNaam",
           WerkplekNaam = "WerkplekNaam",
           Ziekenhuis = "Ziekenhuis",
           ZiekenhuisAfdeling = "ZiekenhuisAfdeling",
           ZiekenhuisAfdelingCode = "ZiekenhuisAfdelingCode",
           Zorglijn = "Zorglijn")
